// =================================================================================
// Code generated by ./web/settings.json. DO NOT EDIT.
// =================================================================================

package settings

var _RawGlobalSettings = `{
  "embedPages": {
    "inbound": {
      "url": "http://localhost:10086/swagger"
    },
    "business": {
      "url": "http://localhost:10087/swagger"
    },
    "monitor": {
      "url": "http://localhost:3000"
    }
  }
}`
