FROM golang:alpine AS builder
WORKDIR /pns
RUN apk add make
ENV GOPROXY=https://proxy.golang.com.cn,direct
COPY .. .
RUN go mod tidy
RUN make all

FROM alpine:3.15.0
WORKDIR /pns
COPY --from=builder /pns/build/pns /pns/pns
COPY --from=builder /pns/config /pns/config
COPY --from=builder /pns/web /pns/web
EXPOSE 10086 10087 10088
VOLUME [ "/pns/log" ]
CMD [ "/pns/pns" ]