{
 "title": "PNS Monitor",
 "description": "PNS Monitor",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "Business", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    { "expr": "rate(request[30s])", "legendFormat": "{{uri}} {{result}}" }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(request_duration_sum[30s]) / rate(request_duration_count[30s])",
     "legendFormat": "{{uri}} {{result}} {{errCode}}"
    }
   ]
  },
  {
   "title": "Push Task Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(push_task_duration_sum[30s]) / rate(push_task_duration_count[30s])",
     "legendFormat": "{{type}} push-{{where}} stage-{{result}}"
    }
   ]
  },
  {
   "title": "In-Memory Event Queue Length",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    { "expr": "event_queue_len", "legendFormat": "{{topic}} queue length" }
   ]
  },
  { "title": "Golang Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(go_gc_cycles_total_gc_cycles_total{job=\"pns\"}[30s])",
     "legendFormat": "GC Frequency"
    },
    {
     "expr": "rate(go_gc_duration_seconds_sum{job=\"pns\"}[30s]) / rate(go_gc_duration_seconds_count{job=\"pns\"}[30s])",
     "legendFormat": "Average GC Duration"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "go_goroutines{job=\"pns\"}",
     "legendFormat": "PNS Goroutines"
    }
   ]
  },
  { "title": "CPU & Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "CPU Load Average",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "node_load1",
     "legendFormat": "Average CPU load in recent 1 minute"
    },
    {
     "expr": "node_load5",
     "legendFormat": "Average CPU load in recent 5 minutes"
    },
    {
     "expr": "node_load15",
     "legendFormat": "Average CPU load in recent 15 minutes"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "1 - avg(irate(node_cpu_seconds_total{mode=\"idle\"}[5m])) by (instance)",
     "legendFormat": "CPU Usage"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes - (node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes))/node_memory_MemTotal_bytes",
     "legendFormat": "Memory Usage"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes - node_memory_SwapFree_bytes)/node_memory_SwapTotal_bytes",
     "legendFormat": "Swap Usage"
    }
   ]
  }
 ]
}