// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/L-LYR/pns/internal/service/internal/dao/internal"
	"github.com/L-LYR/pns/internal/service/internal/do"
)

// _AppConfigDao is the data access object for table app_config.
// You can define custom methods on it to extend its functionality as you wish.
type _AppConfigDao struct {
	*internal.AppConfigDao
}

var (
	// AppConfig is globally public accessible object for table app_config operations.
	AppConfig = _AppConfigDao{
		internal.NewAppConfigDao(),
	}
)

// Fill with you ideas below.

func CreateApp(ctx context.Context, appName string, appId int) error {
	_, err := AppConfig.Ctx(ctx).Insert(
		do.AppConfig{
			Id:   appId,
			Name: appName,
		},
	)
	return err
}
