// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/L-LYR/pns/internal/model"
	"github.com/L-LYR/pns/internal/service/internal/dao/internal"
)

// _AppPusherConfigDao is the data access object for table app_pusher_config.
// You can define custom methods on it to extend its functionality as you wish.
type _AppPusherConfigDao struct {
	*internal.AppPusherConfigDao
}

var (
	// AppPusherConfig is globally public accessible object for table app_pusher_config operations.
	AppPusherConfig = _AppPusherConfigDao{
		internal.NewAppPusherConfigDao(),
	}
)

func FindConfigByKey(ctx context.Context, pusher model.PusherType, appId int, configPointer interface{}) error {
	record, err := AppPusherConfig.
		Ctx(ctx).
		Fields("config").
		Where("pusherId", pusher).
		Where("id", appId).
		One()
	if err != nil {
		return err
	}
	return record.GMap().GetVar("config").Struct(configPointer)
}
