// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"

	"github.com/L-LYR/pns/internal/model"
	"github.com/L-LYR/pns/internal/service/internal/dao/internal"
)

// _TargetDao is the data access object for table target.
// You can define custom methods on it to extend its functionality as you wish.
type _TargetDao struct {
	*internal.TargetDao
}

var (
	// Target is globally public accessible object for table target operations.
	Target = _TargetDao{
		internal.NewTargetDao(),
	}
)

func FindTargetByID(ctx context.Context, deviceId string, appId int) (*model.Target, error) {
	var results []*model.Target
	if res, err := Target.
		Ctx(ctx).
		Where("device_id", deviceId).
		Where("app_id", appId).
		All(); err != nil {
		return nil, err
	} else if res.IsEmpty() {
		return nil, nil
	} else if err = res.Structs(&results); err != nil {
		return nil, err
	} else if len(results) > 1 {
		panic("unreachable")
	} else {
		return results[0], nil
	}
}
