// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"github.com/L-LYR/pns/internal/service/internal/dao/internal"
)

// targetDao is the data access object for table target.
// You can define custom methods on it to extend its functionality as you wish.
type targetDao struct {
	*internal.TargetDao
}

var (
	// Target is globally public accessible object for table target operations.
	Target = targetDao{
		internal.NewTargetDao(),
	}
)

// Fill with you ideas below.
