[owner]
name = "HammerLi"

[server]
[server.inbound]
address = ":10086"
[server.bizapi]
address = ":10087"
[server.admin]
address = ":10088"

[logger]
path = "./log"
file = "{Y-m-d}.log"

[database]
[database.mysql]
host = "mysql"
port = "3306"
user = "root"
pass = "pns_root"
name = "pns"
type = "mysql"
[database.mongo]
host = "mongodb"
port = "27017"
user = "root"
pass = "pns_root"
name = "pns_target"
type = "mongo"

[module]
[module.pusher.mqtt]
broker = "mosquitto"
port = "1883"
timeout = 1
[module.event_queue.push_event_consumer]
topic = "push_event"
dispatch = 5
