[owner]
name = "HammerLi"

[servers]
[servers.inbound]
name = "inbound"
address = ":10086"
[servers.bizapi]
name = "bizapi"
address = ":10087"
[servers.admin]
name = "admin"
address = ":10088"

[logger]
path = "./log"
file = "{Y-m-d}.log"

[database]
[database.mysql]
host = "localhost"
port = "3306"
user = "root"
pass = "pns_root"
name = "pns"
type = "mysql"
[database.mongo]
host = "localhost"
port = "27017"
user = "root"
pass = "pns_root"
name = "pns_target"
type = "mongo"
[database.redis]
host = "localhost"
port = "6379"
pass = "pns_root"

[broker]
broker = "localhost"
port = "1883"
timeout = 1

[event_queue]
[event_queue.task_validation_event_queue]
topic = "task_validation_event"
dispatch = 10
length = 100000
[event_queue.direct_push_task_event_queue]
topic = "direct_push_task_event"
dispatch = 10
length = 100000
[event_queue.range_push_task_event_queue]
topic = "range_push_task_event"
dispatch = 20
length = 100000
[event_queue.broadcast_push_task_event_queue]
topic = "broadcast_push_task_event"
dispatch = 1
length = 10
[event_queue.push_log_event_queue]
topic = "push_log_event"
dispatch = 10
length = 10000

[engine_pool]
min_len = 5
max_len = 10

[misc]
qos = "atLeastOnce"
auth_key_length = 16
auth_secret_length = 32
log_expire_time = 86400           # 24 * 3600 seconds
token_expire_time = 604800        # 7 * 24 * 3600 seconds
message_template_cache_size = 100

[frequency_control]
[frequency_control.app_level]
interval = 3600 # 3600 seconds
limit = 1
[frequency_control.target_level]
interval = 3600 # 3600 seconds
limit = 3
