[owner]
name = "HammerLi"

[servers]
[servers.inbound]
name = "inbound"
address = ":10086"
[servers.bizapi]
name = "bizapi"
address = ":10087"
[servers.admin]
name = "admin"
address = ":10088"

[logger]
path = "./log"
file = "{Y-m-d}.log"

[database]
[database.mysql]
host = "localhost"
port = "3306"
user = "root"
pass = "pns_root"
name = "pns"
type = "mysql"
[database.mongo]
host = "localhost"
port = "27017"
user = "root"
pass = "pns_root"
name = "pns_target"
type = "mongo"
[database.redis]
host = "localhost"
port = "6379"
pass = "pns_root"

[broker]
broker = "localhost"
port = "1883"
timeout = 1

[event_quque]
[event_queue.push_task_event_consumer]
topic = "push_task_event"
dispatch = 5
[event_queue.push_log_event_consumer]
topic = "push_log_event"
dispatch = 5

[misc]
qos = "atLeastOnce"
auth_key_length = 16
auth_secret_length = 32
log_expire_time = 259200   # 3 * 24 * 3600 seconds
token_expire_time = 604800 # 7 * 24 * 3600 seconds
