#!/bin/bash

config_file=$1
output_file=$2

if [ -z "$config_file" ]; then
    echo "config file not found" || exit
fi

config=$(cat "$config_file")

output="package settings\n\n\
// =================================================================================\n\
// Code generated by $config_file. DO NOT EDIT.\n\
// =================================================================================\n\
\n\
var _RawGlobalSettings = \`$config\`\n"

printf "$output" >"$output_file"
