#!/bin/bash

config_file=$1
output_file=$2
package_name=$3

if [ -z "$config_file" ]; then
    echo "config file not found" || exit
fi

config=$(cat "$config_file")

output="// =================================================================================\n\
// Code generated by $config_file. DO NOT EDIT.\n\
// =================================================================================\n\
\n\
package $package_name\n\
\n\
var _RawSettings = \`$config\`\n"

printf "$output" >"$output_file"
