apiVersion: 1
deleteDatasources:
  - name: Prometheus
    orgId: 1
datasources:
  - name: Prometheus
    type: prometheus
    uid: ow25ynQ7z
    access: proxy
    url: http://prometheus:9090
    basicAuth: false
    version: 1
    editable: false
