// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// BizRule is the golang structure of table biz_rule for DAO operations like Where/Data.
type BizRule struct {
	g.Meta      `orm:"table:biz_rule, do:true"`
	Name        interface{} // rule name
	Description interface{} // rule description
	Salience    interface{} // rule salience
	Content     interface{} // rule content
	Status      interface{} // rule status, 0 for disable, 1 for enable
}
