// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-11 00:20:37
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
)

// Target is the golang structure of table target for DAO operations like Where/Data.
type Target struct {
	g.Meta         `orm:"table:target, do:true"`
	DeviceId       interface{} // device id
	Os             interface{} // device os specification
	Brand          interface{} // device brand
	Model          interface{} // device model
	TzName         interface{} // time zone name
	AppId          interface{} // app id
	AppVersion     interface{} // app version string
	PushSdkVersion interface{} // push sdk version string
	CreateTime     interface{} // create time of target
}
