// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// AppConfig is the golang structure for table app_config.
type AppConfig struct {
	Id   int    `json:"id"   ` // app id
	Name string `json:"name" ` // app name
}
