// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// BizRule is the golang structure for table biz_rule.
type BizRule struct {
	Name        string `json:"name"        ` // rule name
	Description string `json:"description" ` // rule description
	Salience    int    `json:"salience"    ` // rule salience
	Content     string `json:"content"     ` // rule content
	Status      int    `json:"status"      ` // rule status, 0 for disable, 1 for enable
}
