// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT. Created at 2022-03-11 00:20:37
// =================================================================================

package entity

import (
	"time"
)

// Target is the golang structure for table target.
type Target struct {
	DeviceId       string    `json:"deviceId"       ` // device id
	Os             string    `json:"os"             ` // device os specification
	Brand          string    `json:"brand"          ` // device brand
	Model          string    `json:"model"          ` // device model
	TzName         string    `json:"tzName"         ` // time zone name
	AppId          int       `json:"appId"          ` // app id
	AppVersion     string    `json:"appVersion"     ` // app version string
	PushSdkVersion string    `json:"pushSdkVersion" ` // push sdk version string
	CreateTime     time.Time `json:"createTime"     ` // create time of target
}
