# Reference: https://prometheus.io/docs/prometheus/latest/configuration/configuration/
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# TODO: Alertmanager configuration

# TODO: Rule configuration

scrape_configs:
  - job_name: "pns" # pns
    static_configs:
      - targets: ["pns:10086"]
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
# TODO: Add other containers
