FROM golang:1.17-alpine3.15 AS builder
WORKDIR /pns
RUN apk add make
ENV GOPROXY=https://proxy.golang.com.cn,direct
COPY . .
RUN go mod tidy
RUN make all

FROM alpine:3.15.0
WORKDIR /pns
COPY --from=builder /pns/build/pns /pns/build/pns
COPY --from=builder /pns/config /pns/build/config
COPY --from=builder /pns/web /pns/build/web
EXPOSE 10086 10087 10088
VOLUME [ "/pns/build/log" ]
CMD [ "/pns/build/pns" ]