// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"
	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// BizRuleDao is the data access object for table biz_rule.
type BizRuleDao struct {
	table   string         // table is the underlying table name of the DAO.
	group   string         // group is the database configuration group name of current DAO.
	columns BizRuleColumns // columns contains all the column names of Table for convenient usage.
}

// BizRuleColumns defines and stores column names for table biz_rule.
type BizRuleColumns struct {
	Name        string // rule name
	Description string // rule description
	Salience    string // rule salience
	Content     string // rule content
	Status      string // rule status, 0 for disable, 1 for enable
}

//  bizRuleColumns holds the columns for table biz_rule.
var bizRuleColumns = BizRuleColumns{
	Name:        "name",
	Description: "description",
	Salience:    "salience",
	Content:     "content",
	Status:      "status",
}

// NewBizRuleDao creates and returns a new DAO object for table data access.
func NewBizRuleDao() *BizRuleDao {
	return &BizRuleDao{
		group:   "mysql",
		table:   "biz_rule",
		columns: bizRuleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *BizRuleDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *BizRuleDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *BizRuleDao) Columns() BizRuleColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *BizRuleDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *BizRuleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *BizRuleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx *gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
